name: "Move Tag"
description: "Move tag if merge was successful"
inputs:
  merged_count:
    description: "Number of successfully merged tasks"
    required: true
  failed_count:
    description: "Number of failed tasks"
    required: true
  tag_name:
    description: "Tag name to move"
    required: true
  branch_name:
    description: "Branch name"
    required: true
  step_name:
    description: "Step name for logging"
    required: true
outputs:
  tag_moved:
    description: "Whether tag was moved"
    value: ${{ steps.move.outputs.tag_moved }}

runs:
  using: "composite"
  steps:
    - name: Move Tag
      id: move
      shell: bash
      run: |
        if [ ${{ inputs.failed_count }} -gt 0 ]; then
          echo "⚠️ Skipping ${{ inputs.tag_name }} tag movement (errors: ${{ inputs.failed_count }}, merged: ${{ inputs.merged_count }})"
          echo "tag_moved=false" >> $GITHUB_OUTPUT
        elif [ ${{ inputs.merged_count }} -gt 0 ]; then
          echo "🏷️ Moving ${{ inputs.tag_name }} tag to current commit..."
          if yarn move-tag "${{ inputs.tag_name }}"; then
            echo "✅ Successfully moved ${{ inputs.tag_name }} tag"
            echo "tag_moved=true" >> $GITHUB_OUTPUT
            
            {
              echo "### 🏷️ ${{ inputs.step_name }} Tag Movement"
              echo "- **Tag:** \`${{ inputs.tag_name }}\`"
              echo "- **Status:** ✅ Successfully moved to current commit"
              echo "- **Branch:** \`${{ inputs.branch_name }}\`"
            } >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Failed to move ${{ inputs.tag_name }} tag"
            echo "tag_moved=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "⚠️ Skipping ${{ inputs.tag_name }} tag movement (no merges)"
          echo "tag_moved=false" >> $GITHUB_OUTPUT
        fi
