name: "Move Tag"
description: "Move tag if merge was successful"
inputs:
  merged_count:
    description: "Number of successfully merged tasks"
    required: true
  failed_count:
    description: "Number of failed tasks"
    required: true
  tag_name:
    description: "Tag name to move"
    required: true
  branch_name:
    description: "Branch name"
    required: true
  step_name:
    description: "Step name for logging"
    required: true
  pat_token: # 💡 新增這個 input
    description: "Personal Access Token for push"
    required: true
outputs:
  tag_moved:
    description: "Whether tag was moved"
    value: ${{ steps.move.outputs.tag_moved }}

runs:
  using: "composite"
  steps:
    - name: Move Tag
      id: move
      shell: bash
      run: |
        if [ ${{ inputs.failed_count }} -gt 0 ]; then
          echo "⚠️ Skipping ${{ inputs.tag_name }} tag movement (errors: ${{ inputs.failed_count }}, merged: ${{ inputs.merged_count }})"
          echo "tag_moved=false" >> $GITHUB_OUTPUT
        elif [ ${{ inputs.merged_count }} -gt 0 ]; then
          echo "🏷️ Moving ${{ inputs.tag_name }} tag to current commit..."
          # 設定 PAT 來推送
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://${{ inputs.pat_token }}@github.com/${{ github.repository }}.git
          
          # 直接執行 tag 操作，不使用 yarn
          TAG_NAME="${{ inputs.tag_name }}"
          echo "🗑️ Deleting local tag: $TAG_NAME"
          git tag -d "${TAG_NAME}" || true
          echo "🗑️ Deleting remote tag: $TAG_NAME"
          git push --delete origin "${TAG_NAME}" || true
          echo "🏷️ Creating new tag: $TAG_NAME"
          git tag -a "${TAG_NAME}" -m "${TAG_NAME}"
          echo "📤 Pushing new tag: $TAG_NAME"
          git push origin "${TAG_NAME}"
          
          if [ $? -eq 0 ]; then
            echo "✅ Successfully moved ${{ inputs.tag_name }} tag"
            echo "tag_moved=true" >> $GITHUB_OUTPUT
            echo "🔍 Debug: Set tag_moved=true" >&2
            
            {
              echo "### 🏷️ ${{ inputs.step_name }} Tag Movement"
              echo "- **Tag:** \`${{ inputs.tag_name }}\`"
              echo "- **Status:** ✅ Successfully moved to current commit"
              echo "- **Branch:** \`${{ inputs.branch_name }}\`"
            } >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Failed to move ${{ inputs.tag_name }} tag"
            echo "tag_moved=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "⚠️ Skipping ${{ inputs.tag_name }} tag movement (no merges)"
          echo "tag_moved=false" >> $GITHUB_OUTPUT
        fi
