name: "Setup Environment"
description: "Setup common environment variables and functions"
inputs:
  branch_type:
    description: "Branch type (beta or delta)"
    required: true
outputs:
  branch_name:
    description: "Generated branch name"
    value: ${{ steps.setup.outputs.branch_name }}
  year:
    description: "Current year (2-digit)"
    value: ${{ steps.setup.outputs.year }}
  week:
    description: "Current week number"
    value: ${{ steps.setup.outputs.week }}

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      id: setup
      shell: bash
      run: |
        # Set up common variables
        export TZ='UTC'
        YEAR=$(date +'%y')
        WEEK=$(date +'%V')

        if [ "${{ inputs.branch_type }}" = "beta" ]; then
          BRANCH_NAME="${{ env.BRANCH_PREFIX_BETA }}-${YEAR}${WEEK}-auto"
        else
          BRANCH_NAME="${{ env.BRANCH_PREFIX_DELTA }}-${YEAR}${WEEK}-auto"
        fi

        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "year=$YEAR" >> $GITHUB_OUTPUT
        echo "week=$WEEK" >> $GITHUB_OUTPUT

        echo "📅 ${{ inputs.branch_type }} branch: $BRANCH_NAME"
