name: "Notify Google Chat"
description: "Send notification to Google Chat with standardized format"
inputs:
  name:
    description: "Notification name"
    required: true
  url:
    description: "Google Chat webhook URL"
    required: true
  type:
    description: "Notification type (success, error, tag_success)"
    required: true
  branch_type:
    description: "Branch type (beta, delta)"
    required: true
  branch_name:
    description: "Branch name"
    required: true
  merged_count:
    description: "Number of merged tasks"
    required: false
    default: "0"
  total_tasks:
    description: "Total number of tasks"
    required: false
    default: "0"
  failed_tasks:
    description: "Failed tasks list"
    required: false
    default: ""
  tag_moved:
    description: "Whether tag was moved"
    required: false
    default: "No"

runs:
  using: "composite"
  steps:
    - name: Send Google Chat Notification
      shell: bash
      run: |
        # 準備訊息內容
        if [ "${{ inputs.type }}" = "success" ]; then
          EMOJI="✅"
          TITLE="${{ inputs.branch_type == 'beta' && 'Beta' || 'Delta' }} Merge Success"
          DESCRIPTION="${{ inputs.branch_type }} tasks have been successfully merged."
          ADDITIONAL_INFO="**Tasks Merged:** ${{ inputs.merged_count }}/${{ inputs.total_tasks }}
        **Tag Moved:** ${{ inputs.tag_moved }}"
        elif [ "${{ inputs.type }}" = "error" ]; then
          EMOJI="❌"
          TITLE="${{ inputs.branch_type == 'beta' && 'Beta' || 'Delta' }} Tasks Processing Failed"
          DESCRIPTION="${{ inputs.branch_type }} task processing has failed. Please check the workflow logs for details."
          ADDITIONAL_INFO="**Failed Tasks:** ${{ inputs.failed_tasks }}"
        else
          EMOJI="✅"
          TITLE="${{ inputs.branch_type == 'beta' && 'Beta' || 'Delta' }} Move Tag Success"
          DESCRIPTION="${{ inputs.branch_type }} tag has been successfully moved to current commit."
          ADDITIONAL_INFO="**Tag:** ${{ inputs.branch_type }}
        **Tasks Merged:** ${{ inputs.merged_count }}/${{ inputs.total_tasks }}"
        fi

        # 構建完整訊息
        MESSAGE="${EMOJI} **${TITLE}**

        ${DESCRIPTION}

        **Repository:** ${GITHUB_REPOSITORY}
        **Branch:** ${{ inputs.branch_name }}
        ${ADDITIONAL_INFO}"

        # 發送到 Google Chat
        curl -X POST \
          -H 'Content-Type: application/json' \
          -d "{\"text\": \"${MESSAGE}\"}" \
          "${{ inputs.url }}"