name: "Notify Google Chat"
description: "Send notification to Google Chat with standardized format"
inputs:
  name:
    description: "Notification name"
    required: true
  url:
    description: "Google Chat webhook URL"
    required: true
  type:
    description: "Notification type (success, error, tag_success)"
    required: true
  branch_type:
    description: "Branch type (beta, delta)"
    required: true
  branch_name:
    description: "Branch name"
    required: true
  merged_count:
    description: "Number of merged tasks"
    required: false
    default: "0"
  total_tasks:
    description: "Total number of tasks"
    required: false
    default: "0"
  failed_tasks:
    description: "Failed tasks list"
    required: false
    default: ""
  failed_branches:
    description: "Failed branches list"
    required: false
    default: ""
  tag_moved:
    description: "Whether tag was moved"
    required: false
    default: "No"
  failed_assignees:
    description: "Failed tasks assignees to mention"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Send Google Chat Notification
      shell: bash
      run: |
        # 準備訊息內容 (測試快取是否存在)
        if [ "${{ inputs.type }}" = "success" ]; then
          EMOJI="🟢"
          TITLE="${{ inputs.branch_type == 'beta' && 'Beta' || 'Delta' }} Merge Success"
          ADDITIONAL_INFO="📁 *Repository:* \`${GITHUB_REPOSITORY}\`
        - *Branch:* \`${{ inputs.branch_name }}\`
        - *Total ${{ inputs.branch_type }} tasks:* ${{ inputs.total_tasks }}
        - *Successfully merged:* ${{ inputs.merged_count }}
        - *Failed:* ${{ inputs.failed_count }}
        - *Tag Moved:* ${{ inputs.tag_moved }}"
        elif [ "${{ inputs.type }}" = "error" ]; then
          EMOJI="🔴"
          TITLE="${{ inputs.branch_type == 'beta' && 'Beta' || 'Delta' }} Tasks Processing Failed"
          
          # Build failed information
          FAILED_INFO="📁 *Repository:* \`${GITHUB_REPOSITORY}\`
        - *Branch:* \`${{ inputs.branch_name }}\`
        - *Total ${{ inputs.branch_type }} tasks:* ${{ inputs.total_tasks }}
        - *Successfully merged:* ${{ inputs.merged_count }}
        - *Failed:* ${{ inputs.failed_count }}"
          
          # Add failed tasks if available
          if [ -n "${{ inputs.failed_tasks }}" ]; then
            FAILED_INFO="${FAILED_INFO}
        ❌ *Failed Tasks:*"
            # Split failed tasks and format as list
            IFS='|' read -ra tasks <<< "${{ inputs.failed_tasks }}"
            for task in "${tasks[@]}"; do
              FAILED_INFO="${FAILED_INFO}
        - ${task}"
            done
          fi
          
          # Add assignee mentions if available
          if [ -n "${{ inputs.failed_assignees }}" ]; then
            FAILED_INFO="${FAILED_INFO}

        👥 *Please check:* ${{ inputs.failed_assignees }}"
          fi
          
          ADDITIONAL_INFO="$FAILED_INFO"
        else
          EMOJI="🟢"
          TITLE="${{ inputs.branch_type == 'beta' && 'Beta' || 'Delta' }} Move Tag Success"
          ADDITIONAL_INFO="📁 *Repository:* \`${GITHUB_REPOSITORY}\`
        🌿 *Branch:* \`${{ inputs.branch_name }}\`
        🏷️ *Tag:* \`${{ inputs.branch_type }}\`
        📊 *Total ${{ inputs.branch_type }} tasks:* ${{ inputs.total_tasks }}
        ✅ *Successfully merged:* ${{ inputs.merged_count }}
        ❌ *Failed:* ${{ inputs.failed_count }}"
        fi

        # 構建完整訊息
        MESSAGE="${EMOJI} *${TITLE}*

        ${ADDITIONAL_INFO}"

        # 發送到 Google Chat
        curl -X POST \
          -H 'Content-Type: application/json' \
          -d "{\"text\": \"${MESSAGE}\"}" \
          "${{ inputs.url }}"
